version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: thecatapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/thecatapi
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      THECATAPI_BASE_URL: https://api.thecatapi.com/v1
      THECATAPI_API_KEY: 
    depends_on:
      - postgres

volumes:
  postgres_data: